# Generated by Django 3.0.2 on 2020-01-11 13:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('finance', 'Finance'), ('hr', 'Human Resource'), ('people', 'People'), ('classroom', 'Classroom')], max_length=30)),
                ('line_manager', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('manager', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='department_manager', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JobGrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(choices=[('12', '12'), ('11', '11'), ('10', '10'), ('9', '9'), ('8', '8'), ('7', '7'), ('6', '6'), ('TM-3', 'TM-3'), ('TM-2', 'TM-2'), ('TM-1', 'TM-1'), ('TM-0', 'TM-0'), ('5', '5'), ('4', '4'), ('1', '1')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='MoringaStaff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.Department')),
                ('job_grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.JobGrade')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'System Admin'), ('user', 'System User')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Relationships',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_work', models.IntegerField()),
                ('stakeholder_management', models.IntegerField()),
                ('conflict_management', models.IntegerField()),
                ('average', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('last_modified', models.DateField(auto_now=True)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('type', models.CharField(choices=[('self', 'Self'), ('manager', 'Manager'), ('final', 'Final')], max_length=30)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.MoringaStaff')),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planning', models.IntegerField()),
                ('execution', models.IntegerField()),
                ('prioritization', models.IntegerField()),
                ('average', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('last_modified', models.DateField(auto_now=True)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('type', models.CharField(choices=[('self', 'Self'), ('manager', 'Manager'), ('final', 'Final')], max_length=30)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.MoringaStaff')),
            ],
        ),
        migrations.AddField(
            model_name='moringastaff',
            name='system_role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.Role'),
        ),
        migrations.AddField(
            model_name='moringastaff',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='InterpersonalCommunication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investment_building', models.IntegerField()),
                ('effective_communication', models.IntegerField()),
                ('delivery', models.IntegerField()),
                ('average', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('last_modified', models.DateField(auto_now=True)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('type', models.CharField(choices=[('self', 'Self'), ('manager', 'Manager'), ('final', 'Final')], max_length=30)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.MoringaStaff')),
            ],
        ),
        migrations.CreateModel(
            name='Innovation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vision_setting', models.IntegerField()),
                ('thinking', models.IntegerField()),
                ('adaptability', models.IntegerField()),
                ('average', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('date', models.DateField(auto_now=True)),
                ('type', models.CharField(choices=[('self', 'Self'), ('manager', 'Manager'), ('final', 'Final')], max_length=30)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.MoringaStaff')),
            ],
        ),
        migrations.CreateModel(
            name='CriticalThinking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_compilation', models.IntegerField()),
                ('data_analysis', models.IntegerField()),
                ('problem_solving', models.IntegerField()),
                ('continual_improvement', models.IntegerField()),
                ('average', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('last_modified', models.DateField(auto_now=True)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('type', models.CharField(choices=[('self', 'Self'), ('manager', 'Manager'), ('final', 'Final')], max_length=30)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.MoringaStaff')),
            ],
        ),
    ]
