# Generated by Django 3.0.2 on 2020-01-12 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='criticalthinking',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='criticalthinking',
            name='last_modified',
        ),
        migrations.RemoveField(
            model_name='criticalthinking',
            name='staff',
        ),
        migrations.RemoveField(
            model_name='criticalthinking',
            name='type',
        ),
        migrations.RemoveField(
            model_name='innovation',
            name='date',
        ),
        migrations.RemoveField(
            model_name='innovation',
            name='staff',
        ),
        migrations.RemoveField(
            model_name='innovation',
            name='type',
        ),
        migrations.RemoveField(
            model_name='interpersonalcommunication',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='interpersonalcommunication',
            name='last_modified',
        ),
        migrations.RemoveField(
            model_name='interpersonalcommunication',
            name='staff',
        ),
        migrations.RemoveField(
            model_name='interpersonalcommunication',
            name='type',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='last_modified',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='staff',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='type',
        ),
        migrations.RemoveField(
            model_name='relationships',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='relationships',
            name='last_modified',
        ),
        migrations.RemoveField(
            model_name='relationships',
            name='staff',
        ),
        migrations.RemoveField(
            model_name='relationships',
            name='type',
        ),
        migrations.AlterField(
            model_name='role',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('admin', 'Admin'), ('user', 'System User')], max_length=20),
        ),
        migrations.CreateModel(
            name='CompetencyResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('self', 'Self'), ('manager', 'Manager'), ('final', 'Final')], max_length=30)),
                ('last_modified', models.DateField(auto_now=True)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('critical_thinking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.CriticalThinking')),
                ('innovation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.Innovation')),
                ('interpersonal_communication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.InterpersonalCommunication')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.Organization')),
                ('relationships', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.Relationships')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.MoringaStaff')),
            ],
        ),
    ]
