# Generated by Django 3.0.2 on 2020-01-12 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_auto_20200112_1701'),
    ]

    operations = [
        migrations.RenameField(
            model_name='criticalthinking',
            old_name='average',
            new_name='score',
        ),
        migrations.RenameField(
            model_name='innovation',
            old_name='average',
            new_name='score',
        ),
        migrations.RenameField(
            model_name='interpersonalcommunication',
            old_name='average',
            new_name='score',
        ),
        migrations.RenameField(
            model_name='organization',
            old_name='average',
            new_name='score',
        ),
        migrations.RenameField(
            model_name='relationships',
            old_name='average',
            new_name='score',
        ),
    ]
