# Generated by Django 3.0.2 on 2020-01-12 14:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('db', '0003_auto_20200112_1725'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moringastaff',
            name='id',
        ),
        migrations.AlterField(
            model_name='moringastaff',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
